INSERT INTO public.hems_bases (name, location, faa_identifier, latitude, longitude, contact)
VALUES 
('Stat MedEvac 1', 'The Washington Hospital', '60PN', 0.0, 0.0, ''),
('Stat MedEvac 2', 'Air Rescue East', 'PA28', 0.0, 0.0, ''),
('Stat MedEvac 3', 'UPMC Passavant - Cranberry', 'PA56', 0.0, 0.0, ''),
('Stat MedEvac 4', 'Allegheny County Airport', 'KAGC', 0.0, 0.0, ''),
('Stat MedEvac 5', 'Joseph A. Hardy Connellsville Airport', 'KVVS', 0.0, 0.0, ''),
('Stat MedEvac 6', 'Clarion County Airport', 'KAXQ', 0.0, 0.0, ''),
('Stat MedEvac 7', 'Port Meadville Airport', 'KGKJ', 0.0, 0.0, ''),
('Stat MedEvac 8', 'Grove City Airport', '29D', 0.0, 0.0, ''),
('Stat MedEvac 9', 'Clearfield-Lawrence Airport', 'KFIG', 0.0, 0.0, ''),
('Stat MedEvac 10', 'John Hopkins Lifeline - John Hopkins Hospital', '0MD3', 0.0, 0.0, ''),
('Stat MedEvac 11', 'UPMC Altoona', '74PN', 0.0, 0.0, ''),
('Stat MedEvac 12', 'UPMC Chautauqua', '4NK0', 0.0, 0.0, ''),
('Stat MedEvac 13', 'York Airport', 'KTHV', 0.0, 0.0, ''),
('Stat MedEvac 14', 'Youngstown Elser Metro Airport', '4G4', 0.0, 0.0, ''),
('Stat MedEvac 15', 'Jefferson County Airpark', '2G2', 0.0, 0.0, ''),
('Stat MedEvac 16', 'Armstrong County Memorial Hospital', '81PN', 0.0, 0.0, ''),
('Stat MedEvac 17', 'Harborcreek Heliport', '39PS', 0.0, 0.0, ''),
('Stat MedEvac 18', 'SkyBear - Children''s National Hospital', 'DC17', 0.0, 0.0, ''),
('AHN LifeFlight 1', 'Cannonsburg Hospital', 'PA67', 0.0, 0.0, ''),
('AHN LifeFlight 2', 'Clarion Hospital', '91PA', 0.0, 0.0, ''),
('AHN LifeFlight 3', 'Indiana Regional Medical Center', 'PN32', 0.0, 0.0, ''),
('AHN LifeFlight 4', 'Pittsburgh/Butler Regional Airport', 'KBTP', 0.0, 0.0, ''),
('AHN LifeFlight 5', 'Rostraver Airport', 'KFWQ', 0.0, 0.0, '');