INSERT INTO public.hems_bases (name, location, faa_identifier, contact, latitude, longitude, helicopter_id)
VALUES
('LifeFlight 1', 'Cannonsburg Hospital', 'PA67', 'Canonsburg Hospital', 40.25, -80.15, (SELECT id FROM public.helicopters WHERE registration = 'N878LF')),
('LifeFlight 2', 'Clarion Hospital', '91PA', 'Clarion Hospital', 41.21, -79.38, (SELECT id FROM public.helicopters WHERE registration = 'N131LF')),
('LifeFlight 3', 'Indiana Regional Medical Center', 'PN32', 'Indiana Regional Medical Center', 40.62, -79.15, (SELECT id FROM public.helicopters WHERE registration = 'N373LF')),
('LifeFlight 4', 'Pittsburgh/Butler Regional Airport', 'KBTP', 'Pittsburgh-Butler Regional Airport', 40.77, -79.95, (SELECT id FROM public.helicopters WHERE registration = 'N474LF')),
('LifeFlight 5', 'Rostraver Airport', 'KFWQ', 'Rostraver Airport', 40.20, -79.85, (SELECT id FROM public.helicopters WHERE registration = 'N575LF')),
('Stat 1', 'The Washington Hospital', '60PN', 'Washington Hospital', 40.17, -80.25, (SELECT id FROM public.helicopters WHERE registration = 'N527ME')),
('Stat 2', 'Air Rescue East', 'PA28', '129 Depot Ave', 40.45, -79.80, (SELECT id FROM public.helicopters WHERE registration = 'N530ME')),
('Stat 3', 'UPMC Passavant - Cranberry', 'PA56', 'UPMC Passavant - Cranberry', 40.70, -80.05, (SELECT id FROM public.helicopters WHERE registration = 'N536ME')),
('Stat 4', 'Allegheny County Airport', 'KAGC', 'Allegheny County Airport - AGC', 40.35, -79.92, (SELECT id FROM public.helicopters WHERE registration = 'N507ME')),
('Stat 5', 'Joseph A. Hardy Connellsville Airport', 'KVVS', 'Joseph A. Hardy Connellsville Airport', 40.00, -79.60, (SELECT id FROM public.helicopters WHERE registration = 'N307ME')),
('Stat 6', 'Clarion County Airport', 'KAXQ', 'Clarion County Airport-Axq', 41.15, -79.45, (SELECT id FROM public.helicopters WHERE registration = 'N533ME')),
('Stat 7', 'Port Meadville Airport', 'KGKJ', 'Port Meadville Airport', 41.65, -80.15, (SELECT id FROM public.helicopters WHERE registration = 'N884ME')),
('Stat 8', 'Grove City Airport', '29D', 'Grove City Airport-29D', 41.15, -80.08, (SELECT id FROM public.helicopters WHERE registration = 'N536ME')),
('Stat 9', 'Clearfield-Lawrence Airport', 'KFIG', 'Clearfield - Lawrence Township Airport', 41.00, -78.40, (SELECT id FROM public.helicopters WHERE registration = 'N855ME')),
('Stat 10', 'John Hopkins Lifeline - John Hopkins Hospital', '0MD3', 'Johns Hopkins Hospital', 39.29, -76.60, (SELECT id FROM public.helicopters WHERE registration = 'N522ME')),
('Stat 11', 'UPMC Altoona', '74PN', 'UPMC-Altoona Heliport', 40.50, -78.40, (SELECT id FROM public.helicopters WHERE registration = 'N448ME')),
('Stat 12', 'UPMC Chautauqua', '4NK0', 'UPMC Chautauqua', 42.10, -79.20, (SELECT id FROM public.helicopters WHERE registration = 'N639ME')),
('Stat 13', 'York Airport', 'KTHV', 'York Airport', 40.00, -76.70, (SELECT id FROM public.helicopters WHERE registration = 'N442ME')),
('Stat 14', 'Youngstown Elser Metro Airport', '4G4', 'Youngstown Elser Metro-4g4', 41.00, -80.60, (SELECT id FROM public.helicopters WHERE registration = 'N446ME')),
('Stat 15', 'Jefferson County Airpark', '2G2', 'Jefferson County Airpark', 40.90, -79.00, (SELECT id FROM public.helicopters WHERE registration = 'N845ME')),
('Stat 16', 'Armstrong County Memorial Hospital', '81PN', 'Armstrong County Memorial Hospital: Lewis John MD', 40.75, -79.50, (SELECT id FROM public.helicopters WHERE registration = 'N915ME')),
('Stat 17', 'Harborcreek Heliport', '39PS', '7201 Buffalo Road', 42.15, -80.00, (SELECT id FROM public.helicopters WHERE registration = 'N932ME')),
('Stat 18', 'SkyBear - Children''s National Hospital', 'DC17', 'Children''s National Med Center', 38.93, -77.01, (SELECT id FROM public.helicopters WHERE registration = 'N87ME'));