INSERT INTO public.hospital_scenery (hospital_id, description, image_urls)
VALUES
((SELECT id FROM public.hospitals WHERE name = 'St Vincent Hospital'), 'Helipad Details: FAA ID 29PN, Surface ASPHALT, Placement ROOFTOP, Dimensions 65 X 65 ft.', '["https://app.box.com/s/gpy4hmah65ibd4uk8zc4vmuuona1o34e"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Canonsburg Hospital'), 'Helipad Details: FAA ID PA67, Surface CONCRETE, Placement GROUND, Dimensions 75 X 75 ft.', '["https://app.box.com/s/jwe3m0l6fu7yf482gydsv9hz8at7pc2x"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Jefferson Hospital'), 'Helipad Details: FAA ID 60PN, Surface CONCRETE/MAT, Placement ROOFTOP, Dimensions 70 x 70 ft.', '["https://app.box.com/s/ifdagwgnv3wreys1rwyb4vt3bdrm658e"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Warren General Hospital'), 'Helipad Details: FAA ID PA97, Surface ASPHALT, Placement GROUND, Dimensions 40 x 40 ft.', '["https://app.box.com/s/dniivq48lnkjqq1yewlq9vl9rce7r6he"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Allegheny General Hospital'), 'Helipad Details: FAA ID 42PN, Surface CONCRETE, Placement ROOFTOP, Dimensions 65 X 65 ft.', '["https://app.box.com/s/kuotdvczh2eik64zydzjnl36jht4sihk"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Butler Memorial Hospital'), 'Helipad Details: FAA ID PA41, Surface ASPHALT, Placement GROUND, Dimensions 65 x 65 ft.', '["https://app.box.com/s/fcvlbx8miwgh1lt08b4k9e5ky4dguubl"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Clarion Hospital'), 'Helipad Details: FAA ID 91PA, Surface CONCRETE, Placement GROUND, Dimensions 50 X 50 ft.', '["https://app.box.com/s/hqlxx7gjtlkppegk1zjigmk7q7lceepc"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Cleveland Clinic Main Campus'), 'Helipad Details: FAA ID 6OI8, Surface CONCRETE, Placement ROOFTOP, Dimensions 50 X 50 ft.', '["https://app.box.com/s/eur9qduiyqgdr3a2srmdvosetojoxvor"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Penn Highlands Jefferson Manor'), 'Helipad Details: FAA ID PA04, Surface ASPHALT, Placement GROUND, Dimensions 65 x 65 ft.', '["https://app.box.com/s/u3fsqs0q1zconri679evmd8wx2np0tg7"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Penn Highlands DuBois'), 'Helipad Details: FAA ID PA10, Surface CONCRETE, Placement GROUND, Dimensions 32 x 32 ft.', '["https://app.box.com/s/7uhlp3k1zzb86usaoucmssdtq06fiicc"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Altoona'), 'Helipad Details: FAA ID 74PN, Surface CONCRETE, Placement ROOFTOP, Dimensions 65 X 65 ft.', '["https://app.box.com/s/xrifdgt86hdekhe0tjiduonr0prore4b"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Children''s Hospital of Pittsburgh'), 'Helipad Details: FAA ID 30PN, Surface CONCRETE, Placement ROOFTOP, Dimensions 45 X 45 ft.', '["https://app.box.com/s/gsf7c8qvmgkwl0i639rani3fjrwiy7rz"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'Forbes Hospital'), 'Helipad Details: FAA ID 54PN, Surface ASPHALT, Placement GROUND, Dimensions 44 X 44 ft.', '["https://app.box.com/s/egkt57c8crf8xgfe50om3tj1m8y7ztj5"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Hamot'), 'Helipad Details: FAA ID 0PS8, Surface CONCRETE, Placement ROOFTOP, Dimensions 60 X 65 ft.', '["https://app.box.com/s/yo1k127lnawoz7vsdmwu4g91urlq0p0h"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Horizon - Shenango Valley'), 'Helipad Details: FAA ID PS41, Surface CONCRETE, Placement GROUND, Dimensions 50 X 50 ft.', '["https://app.box.com/s/xekfv6c8q2hktpb48vdglanj7egmyxm0"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Jameson'), 'Helipad Details: FAA ID 3PN4, Surface CONCRETE, Placement GROUND, Dimensions 44 X 44 ft.', '["https://app.box.com/s/1qjchxgq20okt9eqp78dk8yp5duisq09"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Kane'), 'Helipad Details: FAA ID PA91, Surface ASPHALT, Placement GROUND, Dimensions 60 X 75 ft.', '["https://app.box.com/s/nzepx9a2a4of1udfdb44nrja7wxy5cjw"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Mercy'), 'Helipad Details: FAA ID PN23, Surface CONCRETE, Placement ROOFTOP, Dimensions 65 X 65 ft.', '["https://app.box.com/s/e23snvzp09c5u5htstog5qo9zs1whgeu"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Northwest'), 'Helipad Details: FAA ID PN76, Surface CONCRETE, Placement GROUND, Dimensions 60 X 60 ft.', '["https://app.box.com/s/5he9ty5ves1n8bdxu540trq1swgfgxdu"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Passavant - Cranberry'), 'Helipad Details: FAA ID PA56, Surface CONCRETE, Placement GROUND, Dimensions 60 X 60 ft.', '["https://app.box.com/s/tn5jewsshc6t5q20eygohuszp2dsle59"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC Presbyterian'), 'Helipad Details: FAA ID PS78, Surface CONCRETE, Placement ROOFTOP, Dimensions 96 X 48 ft.', '["https://app.box.com/s/rgi6hbh176dijrdk99bopwmczrg1mcpk"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'UPMC St. Margaret'), 'Helipad Details: FAA ID 46PA, Surface CONCRETE/MAT, Placement ROOFTOP, Dimensions 65 X 65 ft.', '["https://app.box.com/s/yovc7j4uj6tsbclbjfzqbpr1c1mddny0"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'West Penn Hospital'), 'Helipad Details: FAA ID PN80, Surface CONCRETE/MAT, Placement ROOFTOP, Dimensions 40 x 40 ft.', '["https://app.box.com/s/s5e634w7d8a9xe8wn72vswico0mhzzx9"]'::jsonb),
((SELECT id FROM public.hospitals WHERE name = 'AHN Wexford Hospital'), 'Helipad Details: FAA ID 33PA, Surface CONCRETE/MAT, Placement ROOFTOP, Dimensions 53 x 53 ft.', '["https://app.box.com/s/egkt57c8crf8xgfe50om3tj1m8y7ztj5"]'::jsonb)
ON CONFLICT (hospital_id) DO UPDATE
SET description = EXCLUDED.description, image_urls = EXCLUDED.image_urls;